version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  javaservice:
    container_name: javaservice
    restart: on-failure
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"

  dotnetservice:
    container_name: dotnetservice
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=password
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672
      - RedisURL=redis:6379
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro