version: '3.4'

services:
  redis:
    image: redis
  
  rabbitmq:
    image: rabbitmq:management

  dotnetservice:
    image: ${DOCKER_REGISTRY-}dotnetservice
    build:
      context: .
      dockerfile: dotnetService/Dockerfile

