apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: java-service-route
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - worlds.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /java
    backendRefs:
      - name: java-service
        port: 8081
        kind: Service